language: python
arch:
  - amd64
  - ppc64le
  
cache: pip

# Python targets, as defined by https://github.com/travis-ci/travis-build/blob
# /master/spec/build/script/python_spec.rb and https://github.com/travis-ci
# /travis-build/blob/master/lib/travis/build/script/python.rb
python:
  # Standard release https://docs.travis-ci.com/user/languages
  # /python#choosing-python-versions-to-test-against
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

  # PyPy2.7: https://doc.pypy.org/en/latest
  # /index-of-release-notes.html#cpython-2-7-compatible-versions
  - pypy

  # PyPy3.5: https://doc.pypy.org/en/latest
  # /index-of-release-notes.html#cpython-3-3-compatible-versions
  - pypy3

matrix:
  include:
    - python: 2.6
      dist: trusty
    - python: 3.7
      dist: xenial     # required for Python 3.7 (travis-ci/travis-ci#9069)
    - python: 3.8
      dist: xenial     # required for Python 3.8 (travis-ci/travis-ci#9069)
    - python: 3.9
      dist: focal
    - python: nightly
      dist: focal
  # ppc64le related code
    - python: 2.6
      arch: ppc64le
      dist: trusty
    - python: 3.7
      arch: ppc64le
      dist: xenial    
    - python: 3.8
      arch: ppc64le
      dist: xenial    
    - python: 3.9
      arch: ppc64le
      dist: focal
    - python: nightly
      arch: ppc64le
      dist: focal
  
  allow_failures:
    - python: nightly
    - python: nightly
      arch: ppc64le
install: "pip install -r requirements-test.txt"
script: "py.test --doctest-modules boltons tests"
branches:
  except:
    - function_builder
